services:
  mongodb-dev:
    container_name: mongodb-dev
    image: mongo:8-noble
    ports:
      - '27017:27017'
    volumes:
      - mongodb-dev:/data/db
    restart: unless-stopped 
volumes:
  mongodb-dev: